language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
  - jruby-19mode
  - rbx-2
gemfile:
  - gemfiles/rubocop_0.14.1.gemfile
  - gemfiles/rubocop_0.15.0.gemfile
  - gemfiles/rubocop_0.16.0.gemfile
  - gemfiles/rubocop_0.17.0.gemfile
  - gemfiles/rubocop_0.18.1.gemfile
  - gemfiles/rubocop_0.19.1.gemfile
  - gemfiles/rubocop_0.20.1.gemfile
  - gemfiles/rubocop_0.21.0.gemfile
  - gemfiles/rubocop_0.22.0.gemfile
  - gemfiles/rubocop_0.23.0.gemfile
  - gemfiles/rubocop_0.24.0.gemfile
matrix:
  exclude:
    - rvm: 2.1.0
      gemfile: gemfiles/rubocop_0.14.1.gemfile
    - rvm: 2.1.0
      gemfile: gemfiles/rubocop_0.15.0.gemfile
    - rvm: 2.1.0
      gemfile: gemfiles/rubocop_0.16.0.gemfile
    - rvm: 2.1.0
      gemfile: gemfiles/rubocop_0.17.0.gemfile
    - rvm: 2.1.0
      gemfile: gemfiles/rubocop_0.18.1.gemfile
    - rvm: 2.1.0
      gemfile: gemfiles/rubocop_0.19.1.gemfile
  allow_failures:
    - rvm: ruby-head
before_install: gem update --remote bundler
script:
  - bundle exec rake spec
