sudo: false
cache: bundler
language: ruby
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head
  - jruby-9.1.9.0
gemfile:
  - gemfiles/rubocop_0.40.0.gemfile
  - gemfiles/rubocop_0.41.2.gemfile
  - gemfiles/rubocop_0.42.0.gemfile
  - gemfiles/rubocop_0.43.0.gemfile
  - gemfiles/rubocop_0.44.1.gemfile
  - gemfiles/rubocop_0.45.0.gemfile
  - gemfiles/rubocop_0.46.0.gemfile
  - gemfiles/rubocop_0.47.1.gemfile
  - gemfiles/rubocop_0.48.1.gemfile
  - gemfiles/rubocop_0.49.1.gemfile
  - gemfiles/rubocop_0.50.0.gemfile
  - gemfiles/rubocop_0.51.0.gemfile
  - gemfiles/rubocop_0.52.1.gemfile
  - gemfiles/rubocop_0.53.0.gemfile
  - gemfiles/rubocop_0.54.0.gemfile
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
before_install: gem update --remote bundler
install:
  - bundle install --retry=3
script:
  - bundle exec rake spec
